-- CRM Pro multi-tenant foundation
-- This migration converts the original single-installation CRM schema into
-- an organization-scoped SaaS model.
--
-- IMPORTANT: review and test on a non-production Supabase project before
-- applying to any live customer database.

begin;

-- ---------------------------------------------------------------------------
-- Organizations and memberships
-- ---------------------------------------------------------------------------

create table if not exists public.organizations (
  id bigint generated by default as identity primary key,
  name text not null,
  created_at timestamptz not null default now()
);

create table if not exists public.organization_members (
  organization_id bigint not null references public.organizations(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'member'
    check (role in ('owner', 'admin', 'member')),
  created_at timestamptz not null default now(),
  primary key (organization_id, user_id),
  constraint organization_members_one_org_per_user unique (user_id)
);

-- ---------------------------------------------------------------------------
-- Add tenant key to customer-owned tables
-- ---------------------------------------------------------------------------

alter table public.sales add column if not exists organization_id bigint;
alter table public.companies add column if not exists organization_id bigint;
alter table public.contacts add column if not exists organization_id bigint;
alter table public.contact_notes add column if not exists organization_id bigint;
alter table public.deals add column if not exists organization_id bigint;
alter table public.deal_notes add column if not exists organization_id bigint;
alter table public.tags add column if not exists organization_id bigint;
alter table public.tasks add column if not exists organization_id bigint;
alter table public.configuration add column if not exists organization_id bigint;

-- Backfill an existing single-tenant installation into one organization.
do $$
declare
  v_organization_id bigint;
begin
  if exists (select 1 from public.sales) then
    insert into public.organizations(name)
    values ('CRM Pro')
    returning id into v_organization_id;

    update public.sales set organization_id = v_organization_id
      where organization_id is null;
    update public.companies set organization_id = v_organization_id
      where organization_id is null;
    update public.contacts set organization_id = v_organization_id
      where organization_id is null;
    update public.contact_notes set organization_id = v_organization_id
      where organization_id is null;
    update public.deals set organization_id = v_organization_id
      where organization_id is null;
    update public.deal_notes set organization_id = v_organization_id
      where organization_id is null;
    update public.tags set organization_id = v_organization_id
      where organization_id is null;
    update public.tasks set organization_id = v_organization_id
      where organization_id is null;
    update public.configuration set organization_id = v_organization_id
      where organization_id is null;

    insert into public.organization_members(organization_id, user_id, role)
    select
      v_organization_id,
      s.user_id,
      case when s.administrator then 'admin' else 'member' end
    from public.sales s
    on conflict (user_id) do nothing;
  else
    -- The legacy configuration row is global. In a fresh SaaS install,
    -- per-organization configuration is created when the first user signs up.
    delete from public.configuration where organization_id is null;
  end if;
end
$$;

alter table public.sales alter column organization_id set not null;
alter table public.companies alter column organization_id set not null;
alter table public.contacts alter column organization_id set not null;
alter table public.contact_notes alter column organization_id set not null;
alter table public.deals alter column organization_id set not null;
alter table public.deal_notes alter column organization_id set not null;
alter table public.tags alter column organization_id set not null;
alter table public.tasks alter column organization_id set not null;
alter table public.configuration alter column organization_id set not null;

alter table public.sales
  add constraint sales_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.companies
  add constraint companies_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.contacts
  add constraint contacts_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.contact_notes
  add constraint contact_notes_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.deals
  add constraint deals_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.deal_notes
  add constraint deal_notes_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.tags
  add constraint tags_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.tasks
  add constraint tasks_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;
alter table public.configuration
  add constraint configuration_organization_id_fkey
  foreign key (organization_id) references public.organizations(id) on delete cascade;

create index if not exists sales_organization_id_idx on public.sales(organization_id);
create index if not exists companies_organization_id_idx on public.companies(organization_id);
create index if not exists contacts_organization_id_idx on public.contacts(organization_id);
create index if not exists contact_notes_organization_id_idx on public.contact_notes(organization_id);
create index if not exists deals_organization_id_idx on public.deals(organization_id);
create index if not exists deal_notes_organization_id_idx on public.deal_notes(organization_id);
create index if not exists tags_organization_id_idx on public.tags(organization_id);
create index if not exists tasks_organization_id_idx on public.tasks(organization_id);
create index if not exists configuration_organization_id_idx on public.configuration(organization_id);

-- Configuration remains id=1 inside each organization.
alter table public.configuration drop constraint if exists configuration_pkey;
alter table public.configuration
  add constraint configuration_pkey primary key (organization_id, id);

-- ---------------------------------------------------------------------------
-- Tenant helper functions
-- ---------------------------------------------------------------------------

create or replace function public.current_organization_id()
returns bigint
language sql
stable
security definer
set search_path = ''
as $$
  select om.organization_id
  from public.organization_members om
  where om.user_id = auth.uid()
  limit 1
$$;

create or replace function public.is_org_member(target_organization_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.organization_members om
    where om.user_id = auth.uid()
      and om.organization_id = target_organization_id
  )
$$;

create or replace function public.is_org_admin(target_organization_id bigint)
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.sales s
    where s.user_id = auth.uid()
      and s.organization_id = target_organization_id
      and s.administrator = true
      and s.disabled = false
  )
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select public.is_org_admin(public.current_organization_id())
$$;

-- Set both the salesperson and organization on new customer-owned records.
create or replace function public.set_sales_id_default()
returns trigger
language plpgsql
set search_path = 'public'
as $$
declare
  v_organization_id bigint;
begin
  v_organization_id := public.current_organization_id();

  if v_organization_id is null then
    raise exception 'Authenticated user is not associated with an organization';
  end if;

  if new.organization_id is null then
    new.organization_id := v_organization_id;
  elsif new.organization_id <> v_organization_id then
    raise exception 'Cross-organization insert is not allowed';
  end if;

  if new.sales_id is null then
    select id into new.sales_id
    from public.sales
    where user_id = auth.uid()
      and organization_id = v_organization_id;
  end if;

  return new;
end
$$;

create or replace function public.set_organization_id_default()
returns trigger
language plpgsql
set search_path = 'public'
as $$
declare
  v_organization_id bigint;
begin
  v_organization_id := public.current_organization_id();

  if v_organization_id is null then
    raise exception 'Authenticated user is not associated with an organization';
  end if;

  if new.organization_id is null then
    new.organization_id := v_organization_id;
  elsif new.organization_id <> v_organization_id then
    raise exception 'Cross-organization insert is not allowed';
  end if;

  return new;
end
$$;

-- New public signups create a new organization.
-- Invited users can only join an existing organization when organization_id is
-- placed in raw_app_meta_data by an admin/service-role call.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_organization_id bigint;
  v_role text;
  v_org_name text;
begin
  v_organization_id := nullif(new.raw_app_meta_data ->> 'organization_id', '')::bigint;

  if v_organization_id is not null then
    if not exists (
      select 1 from public.organizations o where o.id = v_organization_id
    ) then
      raise exception 'Invited organization does not exist';
    end if;

    v_role := case
      when new.raw_app_meta_data ->> 'organization_role' in ('admin', 'member')
        then new.raw_app_meta_data ->> 'organization_role'
      else 'member'
    end;
  else
    v_org_name := coalesce(
      nullif(new.raw_user_meta_data ->> 'organization_name', ''),
      nullif(trim(concat(
        coalesce(new.raw_user_meta_data ->> 'first_name', ''),
        ' ',
        coalesce(new.raw_user_meta_data ->> 'last_name', '')
      )), ''),
      'Minha empresa'
    );

    insert into public.organizations(name)
    values (v_org_name)
    returning id into v_organization_id;

    v_role := 'owner';
  end if;

  insert into public.organization_members(organization_id, user_id, role)
  values (v_organization_id, new.id, v_role);

  insert into public.sales(
    first_name,
    last_name,
    email,
    user_id,
    administrator,
    organization_id
  )
  values (
    coalesce(
      new.raw_user_meta_data ->> 'first_name',
      new.raw_user_meta_data -> 'custom_claims' ->> 'first_name',
      'Pending'
    ),
    coalesce(
      new.raw_user_meta_data ->> 'last_name',
      new.raw_user_meta_data -> 'custom_claims' ->> 'last_name',
      'Pending'
    ),
    new.email,
    new.id,
    v_role in ('owner', 'admin'),
    v_organization_id
  );

  insert into public.configuration(organization_id, id, config)
  values (v_organization_id, 1, '{}'::jsonb)
  on conflict (organization_id, id) do nothing;

  return new;
end
$$;

-- ---------------------------------------------------------------------------
-- Tenant-aware triggers
-- ---------------------------------------------------------------------------

drop trigger if exists set_tag_organization_id_trigger on public.tags;
create trigger set_tag_organization_id_trigger
  before insert on public.tags
  for each row execute function public.set_organization_id_default();

-- Existing business-table triggers already call set_sales_id_default().
-- The function above now also assigns and validates organization_id.

-- ---------------------------------------------------------------------------
-- Recreate tenant-aware views
-- ---------------------------------------------------------------------------

drop view if exists public.activity_log;
create view public.activity_log with (security_invoker = on) as
select
    ('company.' || c.id || '.created') as id,
    'company.created' as type,
    c.created_at as date,
    c.id as company_id,
    c.sales_id,
    to_json(c.*) as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note,
    c.organization_id
from public.companies c
union all
select
    ('contact.' || co.id || '.created') as id,
    'contact.created' as type,
    co.first_seen as date,
    co.company_id,
    co.sales_id,
    null::json as company,
    to_json(co.*) as contact,
    null::json as deal,
    null::json as contact_note,
    null::json as deal_note,
    co.organization_id
from public.contacts co
union all
select
    ('contactNote.' || cn.id || '.created') as id,
    'contactNote.created' as type,
    cn.date,
    co.company_id,
    cn.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    to_json(cn.*) as contact_note,
    null::json as deal_note,
    cn.organization_id
from public.contact_notes cn
left join public.contacts co on co.id = cn.contact_id
union all
select
    ('deal.' || d.id || '.created') as id,
    'deal.created' as type,
    d.created_at as date,
    d.company_id,
    d.sales_id,
    null::json as company,
    null::json as contact,
    to_json(d.*) as deal,
    null::json as contact_note,
    null::json as deal_note,
    d.organization_id
from public.deals d
union all
select
    ('dealNote.' || dn.id || '.created') as id,
    'dealNote.created' as type,
    dn.date,
    d.company_id,
    dn.sales_id,
    null::json as company,
    null::json as contact,
    null::json as deal,
    null::json as contact_note,
    to_json(dn.*) as deal_note,
    dn.organization_id
from public.deal_notes dn
left join public.deals d on d.id = dn.deal_id;

drop view if exists public.companies_summary;
create view public.companies_summary with (security_invoker = on) as
select
    c.id,
    c.created_at,
    c.name,
    c.sector,
    c.size,
    c.linkedin_url,
    c.website,
    c.phone_number,
    c.address,
    c.zipcode,
    c.city,
    c.state_abbr,
    c.sales_id,
    c.context_links,
    c.country,
    c.description,
    c.revenue,
    c.tax_identifier,
    c.logo,
    c.organization_id,
    count(distinct d.id) as nb_deals,
    count(distinct co.id) as nb_contacts
from public.companies c
left join public.deals d
  on c.id = d.company_id and d.organization_id = c.organization_id
left join public.contacts co
  on c.id = co.company_id and co.organization_id = c.organization_id
group by c.id;

drop view if exists public.contacts_summary;
create view public.contacts_summary with (security_invoker = on) as
select
    co.id,
    co.first_name,
    co.last_name,
    co.gender,
    co.title,
    co.background,
    co.avatar,
    co.first_seen,
    co.last_seen,
    co.has_newsletter,
    co.status,
    co.tags,
    co.company_id,
    co.sales_id,
    co.linkedin_url,
    co.email_jsonb,
    co.phone_jsonb,
    co.organization_id,
    (jsonb_path_query_array(co.email_jsonb, '$[*]."email"'))::text as email_fts,
    (jsonb_path_query_array(co.phone_jsonb, '$[*]."number"'))::text as phone_fts,
    c.name as company_name,
    count(distinct t.id) filter (where t.done_date is null) as nb_tasks
from public.contacts co
left join public.tasks t
  on co.id = t.contact_id and t.organization_id = co.organization_id
left join public.companies c
  on co.company_id = c.id and c.organization_id = co.organization_id
group by co.id, c.name;

drop view if exists public.init_state;
create view public.init_state with (security_invoker = on) as
select count(*) as is_initialized
from public.sales s
where s.user_id = auth.uid();

-- ---------------------------------------------------------------------------
-- Row Level Security
-- ---------------------------------------------------------------------------

alter table public.organizations enable row level security;
alter table public.organization_members enable row level security;

do $$
declare
  p record;
begin
  for p in
    select schemaname, tablename, policyname
    from pg_policies
    where schemaname = 'public'
      and tablename = any(array[
        'organizations',
        'organization_members',
        'companies',
        'contacts',
        'contact_notes',
        'deals',
        'deal_notes',
        'sales',
        'tags',
        'tasks',
        'configuration',
        'favicons_excluded_domains'
      ])
  loop
    execute format(
      'drop policy if exists %I on %I.%I',
      p.policyname,
      p.schemaname,
      p.tablename
    );
  end loop;
end
$$;

create policy organizations_select
  on public.organizations for select to authenticated
  using (public.is_org_member(id));

create policy organizations_update
  on public.organizations for update to authenticated
  using (public.is_org_admin(id))
  with check (public.is_org_admin(id));

create policy organization_members_select
  on public.organization_members for select to authenticated
  using (organization_id = public.current_organization_id());

create policy sales_select
  on public.sales for select to authenticated
  using (organization_id = public.current_organization_id());

create policy companies_tenant_access
  on public.companies for all to authenticated
  using (organization_id = public.current_organization_id())
  with check (organization_id = public.current_organization_id());

create policy contacts_tenant_access
  on public.contacts for all to authenticated
  using (organization_id = public.current_organization_id())
  with check (organization_id = public.current_organization_id());

create policy contact_notes_tenant_access
  on public.contact_notes for all to authenticated
  using (organization_id = public.current_organization_id())
  with check (organization_id = public.current_organization_id());

create policy deals_tenant_access
  on public.deals for all to authenticated
  using (organization_id = public.current_organization_id())
  with check (organization_id = public.current_organization_id());

create policy deal_notes_tenant_access
  on public.deal_notes for all to authenticated
  using (organization_id = public.current_organization_id())
  with check (organization_id = public.current_organization_id());

create policy tags_tenant_access
  on public.tags for all to authenticated
  using (organization_id = public.current_organization_id())
  with check (organization_id = public.current_organization_id());

create policy tasks_tenant_access
  on public.tasks for all to authenticated
  using (organization_id = public.current_organization_id())
  with check (organization_id = public.current_organization_id());

create policy configuration_select
  on public.configuration for select to authenticated
  using (organization_id = public.current_organization_id());

create policy configuration_insert
  on public.configuration for insert to authenticated
  with check (
    organization_id = public.current_organization_id()
    and public.is_org_admin(organization_id)
  );

create policy configuration_update
  on public.configuration for update to authenticated
  using (
    organization_id = public.current_organization_id()
    and public.is_org_admin(organization_id)
  )
  with check (
    organization_id = public.current_organization_id()
    and public.is_org_admin(organization_id)
  );

-- Favicons are global reference data. Clients may read them but not mutate them.
create policy favicons_select
  on public.favicons_excluded_domains for select to authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- Storage isolation
-- ---------------------------------------------------------------------------

drop policy if exists "Attachments 1mt4rzk_0" on storage.objects;
drop policy if exists "Attachments 1mt4rzk_1" on storage.objects;
drop policy if exists "Attachments 1mt4rzk_3" on storage.objects;
drop policy if exists attachments_tenant_select on storage.objects;
drop policy if exists attachments_tenant_insert on storage.objects;
drop policy if exists attachments_tenant_update on storage.objects;
drop policy if exists attachments_tenant_delete on storage.objects;

insert into storage.buckets(id, name, public)
values ('attachments', 'attachments', false)
on conflict (id) do update set public = false;

-- Branding assets are intentionally public, but only members of the owning
-- organization may create, replace or delete objects under its folder.
insert into storage.buckets(id, name, public)
values ('branding', 'branding', true)
on conflict (id) do update set public = true;

drop policy if exists branding_tenant_insert on storage.objects;
drop policy if exists branding_tenant_update on storage.objects;
drop policy if exists branding_tenant_delete on storage.objects;

create policy attachments_tenant_select
  on storage.objects for select to authenticated
  using (
    bucket_id = 'attachments'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  );

create policy attachments_tenant_insert
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'attachments'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  );

create policy attachments_tenant_update
  on storage.objects for update to authenticated
  using (
    bucket_id = 'attachments'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  )
  with check (
    bucket_id = 'attachments'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  );

create policy attachments_tenant_delete
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'attachments'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  );

create policy branding_tenant_insert
  on storage.objects for insert to authenticated
  with check (
    bucket_id = 'branding'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  );

create policy branding_tenant_update
  on storage.objects for update to authenticated
  using (
    bucket_id = 'branding'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  )
  with check (
    bucket_id = 'branding'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  );

create policy branding_tenant_delete
  on storage.objects for delete to authenticated
  using (
    bucket_id = 'branding'
    and (storage.foldername(name))[1] = public.current_organization_id()::text
  );

-- ---------------------------------------------------------------------------
-- Grants
-- ---------------------------------------------------------------------------

grant select on public.organizations to authenticated;
grant select on public.organization_members to authenticated;

grant execute on function public.current_organization_id() to authenticated;
grant execute on function public.is_org_member(bigint) to authenticated;
grant execute on function public.is_org_admin(bigint) to authenticated;
grant execute on function public.set_organization_id_default() to authenticated;

grant all on table public.organizations to service_role;
grant all on table public.organization_members to service_role;
grant all on sequence public.organizations_id_seq to service_role;

grant select on public.activity_log to authenticated;
grant select on public.companies_summary to authenticated;
grant select on public.contacts_summary to authenticated;
grant select on public.init_state to anon, authenticated;

commit;
